name: Compile Synergy with Qt5

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: symless/synergy-core

      - name: Set up dependencies
        run: |
          brew update
          brew install cmake openssl avahi
          brew install qt@5

      - name: Configure CMake
        run: cmake -Bbuild -H. -DCMAKE_PREFIX_PATH=$(brew --prefix qt@5)

      - name: Build
        run: cmake --build build --config Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: synergy-macos
          path: build

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: symless/synergy-core

      - name: Set up dependencies
        run: |
          choco install cmake
          choco install openssl
          choco install qt5

      - name: Configure CMake
        run: cmake -Bbuild -H. -G "Visual Studio 16 2019" -A x64 -DCMAKE_PREFIX_PATH="C:\tools\qt5"

      - name: Build
        run: cmake --build build --config Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: synergy-windows
          path: build

  create-release:
    runs-on: ubuntu-latest
    needs: [build-macos, build-windows]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: symless/synergy-core

      - name: Download macOS build artifacts
        uses: actions/download-artifact@v2
        with:
          name: synergy-macos
          path: ./artifacts/macos

      - name: Download Windows build artifacts
        uses: actions/download-artifact@v2
        with:
          name: synergy-windows
          path: ./artifacts/windows

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: "Synergy Release ${{ github.ref }}"
          body: |
            Release for Synergy version ${{ github.ref }}.
          draft: false
          prerelease: false

      - name: Upload Release Assets for macOS
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/macos
          asset_name: synergy-macos-${{ github.ref }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload Release Assets for Windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/windows
          asset_name: synergy-windows-${{ github.ref }}.zip
          asset_content_type: application/zip
